[font]
size = 11.0

[window]
opacity = 0.85

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window.padding]
x = 6
y = 6

[colors.normal]
black = "#2d2424"
red = "#cf223e"
green = "#959a6b"
yellow = "#e39c45"
blue = "#614f76"
magenta = "#ae3f82"
cyan = "#756d94"
white = "#ffe9c7"

[colors.bright]
black = "#c1aeae"
red = "#ae4750"
green = "#97916f"
yellow = "#cd9165"
blue = "#83546b"
magenta = "#a05a78"
cyan = "#79657a"
white = "#2d2424"
