[font]
size = 12.0

[scrolling]
history = 100

[window]
opacity = 0.97

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window.padding]
x = 15
y = 15

[colors.bright]
black = "#c1aeae"
blue = "#83546b"
cyan = "#79657a"
green = "#97916f"
magenta = "#a05a78"
red = "#ae4750"
white = "#2d2424"
yellow = "#cd9165"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#2d2424"
blue = "#614f76"
cyan = "#756d94"
green = "#959a6b"
magenta = "#ae3f82"
red = "#cf223e"
white = "#ffe9c7"
yellow = "#e39c45"

[colors.primary]
background = "#1e2327"
foreground = "#d3c6aa"
